### ISSUE TITLE
ipfshttpclient.exception raised when using ethpm list

### ISSUE THREAD

**Issue by yogh333** [ethpm/ethpm-cli#100]
_If this is a bug report, please fill in the following sections.
If this is a feature request, delete and describe what you would like with examples._

## What was wrong?
Unable to use ethos client
### Code that produced the error

```py
ethpm list
```

### Full error output 

```sh
ethPM CLI: A command line tool for the Ethereum Package Manager. v0.2.0

Traceback (most recent call last):
  File "/usr/local/bin/ethpm", line 33, in <module>
    sys.exit(load_entry_point('ethpm-cli==0.2.0', 'console_scripts', 'ethpm')())
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ethpm_cli/main.py", line 16, in main
    args.func(args)
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ethpm_cli/parser.py", line 534, in list_action
    config = Config(args)
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ethpm_cli/config.py", line 47, in __init__
    self.ipfs_backend = get_ipfs_backend()
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ethpm_cli/_utils/ipfs.py", line 7, in get_ipfs_backend
    return InfuraIPFSBackend()
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ethpm/backends/ipfs.py", line 78, in __init__
    self.client = ipfshttpclient.connect(self.base_uri)
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py", line 101, in connect
    assert_version(client.version()['Version'])
  File "/usr/local/Cellar/ethpm-cli/0.2.0/libexec/lib/python3.8/site-packages/ipfshttpclient/client/__init__.py", line 66, in assert_version
    raise exceptions.VersionMismatch(version, minimum, maximum)
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '[0, 5, 1]' (not in range: [0, 4, 3] – [0, 5, 0])
```

### Environment

```sh
# run this:
$ python -m eth_utils

# then copy the output here:
/Users/jcaporossi/.pyenv/shims/python: line 21: /usr/local/Cellar/pyenv/1.2.19/libexec/pyenv: No such file or directory
``` 

## How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by njgheorghita** [comment]
Hey @jcaporossi I'm not familiar with the ethos client. Can you explain what it is and/or what is the expected behavior here within the ethpm context?

**Comment by yogh333** [comment]
Oops, sorry for the typo but I am talking about **ethpm** client.

**Comment by njgheorghita** [comment]
It's somewhat difficult to figure out what's going wrong in this situation. Did this error occur after following the [quickstart](https://ethpm-cli.readthedocs.io/en/latest/quickstart.html)?

**Comment by nyg** [comment]
I'm having the same issue when using the Docker image:

```
$ docker run -i -e WEB3_INFURA_PROJECT_ID=xxx ethpm/ethpm:v0.2.0 get ethpm://zeppelin.snakecharmers.eth:1/math@1.0.0


ethPM CLI: A command line tool for the Ethereum Package Manager. v0.2.0

Traceback (most recent call last):
  File "/usr/local/bin/ethpm", line 11, in <module>
    load_entry_point('ethpm-cli', 'console_scripts', 'ethpm')()
  File "/usr/src/app/ethpm_cli/main.py", line 16, in main
    args.func(args)
  File "/usr/src/app/ethpm_cli/parser.py", line 574, in get_action
    config = Config(args)
  File "/usr/src/app/ethpm_cli/config.py", line 47, in __init__
    self.ipfs_backend = get_ipfs_backend()
  File "/usr/src/app/ethpm_cli/_utils/ipfs.py", line 7, in get_ipfs_backend
    return InfuraIPFSBackend()
  File "/usr/local/lib/python3.7/site-packages/ethpm/backends/ipfs.py", line 78, in __init__
    self.client = ipfshttpclient.connect(self.base_uri)
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/client/__init__.py", line 101, in connect
    assert_version(client.version()['Version'])
  File "/usr/local/lib/python3.7/site-packages/ipfshttpclient/client/__init__.py", line 66, in assert_version
    raise exceptions.VersionMismatch(version, minimum, maximum)
ipfshttpclient.exceptions.VersionMismatch: Unsupported daemon version '[0, 7, 0]' (not in range: [0, 4, 3] – [0, 5, 0])
```
